from crewai import Task


def create_fact_check_task(fact_checker_agent, writing_task):
    return Task(
        description=(
            "Review the report generated by the Writer Agent. "
            "Identify any factual inaccuracies, unsupported claims, "
            "logical inconsistencies, or misleading statements. "
            "Suggest corrections wherever necessary."
        ),

        expected_output=(
            "A verified report that includes:\n"
            "- Verified facts\n"
            "- Any incorrect statements found\n"
            "- Suggested corrections\n"
            "- Overall assessment of the report's accuracy"
        ),

        agent=fact_checker_agent,

        context=[writing_task]
    )